GET http://localhost:4444

###

POST http://localhost:4444/init
Content-Type: application/json

{
    "secret": "12345",
    "adminpassword": "cisco"
}

###
POST http://localhost:4444/login
Content-Type: application/json

{
    "username": "admin",
    "password": "cisco"
}

###

GET http://localhost:4444/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicnVvbG8iOiJhZG1pbmlzdHJhdG9yIiwiaWF0IjoxNzMzMTUxNDYxLCJleHAiOjE3MzMxNTUwNjF9.v6cQFHu4291VwK0ToBP8AiA0YdXBbAHv09DyngCBdAs

###
GET http://localhost:4444/users/1

###
DELETE http://localhost:4444/users/1
